@echo off

echo compiling Minicraft.java...
javac Minicraft.java

echo compiling MinicraftPanel.java...
javac MinicraftPanel.java

echo Compiling folder Block...
javac Block/*.java

echo Compiling folder Render...
javac Render/*.java

echo Compiling folder Util...
javac Util/*.java

echo Compiling folder World...
javac World/*.java

echo Compiling folder Player...
javac Player/*.java

echo Compiling folder UI...
javac UI/*.java

echo Compiling folder Item...
javac Item/*.java

echo Running game...
echo =====================
java Minicraft